export const CHANGE_FILTER_STATE = "CHANGE_FILTER_STATE"
export const CHANGE_FILTER_STATE_SUCCESS = "CHANGE_FILTER_STATE_SUCCESS"
export const CHANGE_FILTER_STATE_FAILURE = "CHANGE_FILTER_STATE_FAILURE"
export const CHANGE_IS_WARNING = "CHANGE_IS_WARNING"
export const CHANGE_IS_WARNING_SUCCESS = "CHANGE_IS_WARNING_SUCCESS"

export const CHANGE_SENSOR_FILTER_STATE = "CHANGE_SENSOR_FILTER_STATE"
export const CHANGE_SENSOR_FILTER_STATE_SUCCESS = "CHANGE_SENSOR_FILTER_STATE_SUCCESS"
export const CHANGE_SENSOR_FILTER_STATE_FAILURE = "CHANGE_SENSOR_FILTER_STATE_FAILURE"
